Repository KU-eSports/kuest-streaming, pull requests merged in 2022-11, with the labels that each got.

#59 add overlay
  .gitignore
  obs/overlay/game_highlights.png
  obs/overlay/today_highlights.png
Labels: タイプ: 機能追加, 状態: 確認必要

#63 waiting layout の実装
  package-lock.json
  src/browser/graphics/waiting/component/agent.tsx
  src/browser/graphics/waiting/component/background.tsx
  src/browser/graphics/waiting/component/splats.tsx
  src/browser/graphics/waiting/component/stickers.tsx
  src/browser/graphics/waiting/component/telop.tsx
  src/browser/graphics/waiting/component/timer.tsx
  src/browser/graphics/waiting/css/agent.module.css
  src/browser/graphics/waiting/css/background.module.css
  src/browser/graphics/waiting/css/splats.css
  src/browser/graphics/waiting/css/stickers.css
  src/browser/graphics/waiting/css/style.module.css
  src/browser/graphics/waiting/css/telop.module.css
  src/browser/graphics/waiting/css/timer.module.css
  src/browser/graphics/waiting/image/bgpattern.svg
  src/browser/graphics/waiting/image/bluesplats.svg
  src/browser/graphics/waiting/image/decosplat.svg
  src/browser/graphics/waiting/image/decosplat2.svg
  src/browser/graphics/waiting/image/sticker_kuest.svg
  src/browser/graphics/waiting/image/sticker_logo.svg
  src/browser/graphics/waiting/image/sticker_panic.svg
  src/browser/graphics/waiting/image/sticker_wink.svg
  src/browser/graphics/waiting/image/stickers.svg
  src/browser/graphics/waiting/image/telopsplat.svg
  src/browser/graphics/waiting/image/timerarrow.svg
  src/browser/graphics/waiting/image/timersplat.svg
  src/browser/graphics/waiting/index.tsx
  src/browser/graphics/waiting/script/api.ts
Labels: タイプ: 修正, 作業: 実装作業, 優先度: 高

#70 Splatoon3 overlay
  src/browser/graphics/talk/component/voice.tsx
  src/browser/graphics/talk/css/voice.module.css
Labels: タイプ: 修正, 優先度: 緊急
